-- =============================================================
-- Migración 0002: datos geográficos oficiales (códigos INE)
-- Comunidades autónomas y provincias de España
-- =============================================================

insert into public.comunidades (id, nombre) values
  (1,  'Andalucía'),
  (2,  'Aragón'),
  (3,  'Principado de Asturias'),
  (4,  'Illes Balears'),
  (5,  'Canarias'),
  (6,  'Cantabria'),
  (7,  'Castilla y León'),
  (8,  'Castilla-La Mancha'),
  (9,  'Cataluña'),
  (10, 'Comunitat Valenciana'),
  (11, 'Extremadura'),
  (12, 'Galicia'),
  (13, 'Comunidad de Madrid'),
  (14, 'Región de Murcia'),
  (15, 'Comunidad Foral de Navarra'),
  (16, 'País Vasco'),
  (17, 'La Rioja'),
  (18, 'Ceuta'),
  (19, 'Melilla')
on conflict (id) do nothing;

insert into public.provincias (id, nombre, comunidad_id) values
  (1,  'Álava/Araba', 16),
  (2,  'Albacete', 8),
  (3,  'Alicante/Alacant', 10),
  (4,  'Almería', 1),
  (5,  'Ávila', 7),
  (6,  'Badajoz', 11),
  (7,  'Illes Balears', 4),
  (8,  'Barcelona', 9),
  (9,  'Burgos', 7),
  (10, 'Cáceres', 11),
  (11, 'Cádiz', 1),
  (12, 'Castellón/Castelló', 10),
  (13, 'Ciudad Real', 8),
  (14, 'Córdoba', 1),
  (15, 'A Coruña', 12),
  (16, 'Cuenca', 8),
  (17, 'Girona', 9),
  (18, 'Granada', 1),
  (19, 'Guadalajara', 8),
  (20, 'Gipuzkoa', 16),
  (21, 'Huelva', 1),
  (22, 'Huesca', 2),
  (23, 'Jaén', 1),
  (24, 'León', 7),
  (25, 'Lleida', 9),
  (26, 'La Rioja', 17),
  (27, 'Lugo', 12),
  (28, 'Madrid', 13),
  (29, 'Málaga', 1),
  (30, 'Murcia', 14),
  (31, 'Navarra', 15),
  (32, 'Ourense', 12),
  (33, 'Asturias', 3),
  (34, 'Palencia', 7),
  (35, 'Las Palmas', 5),
  (36, 'Pontevedra', 12),
  (37, 'Salamanca', 7),
  (38, 'Santa Cruz de Tenerife', 5),
  (39, 'Cantabria', 6),
  (40, 'Segovia', 7),
  (41, 'Sevilla', 1),
  (42, 'Soria', 7),
  (43, 'Tarragona', 9),
  (44, 'Teruel', 2),
  (45, 'Toledo', 8),
  (46, 'Valencia/València', 10),
  (47, 'Valladolid', 7),
  (48, 'Bizkaia', 16),
  (49, 'Zamora', 7),
  (50, 'Zaragoza', 2),
  (51, 'Ceuta', 18),
  (52, 'Melilla', 19)
on conflict (id) do nothing;
